export const btn: string;
export const checkbox: string;
export const completed: string;
export const dates: string;
export const del: string;
export const fade: string;
export const rising: string;
export const subject: string;
export const task: string;
