export const app: string;
export const content: string;
export const contentTasks: string;
export const header: string;
export const headerClear: string;
export const headerContent: string;
export const headerCreate: string;
export const headerHead: string;
export const materialSymbols: string;
