export enum TASK_STATE {
  REMOVE_TASK = "REMOVE_TASK",
  ADD_TASK = "ADD_TASK",
  EDIT_TASK = "EDIT_TASK",
  CLEAR_TASKS = "CLEAR_TASKS",
  SET_CURRENT_ID = "SET_CURRENT_ID",
  TOGGLE_TASK_COMPLETED = "TOGGLE_TASK_COMPLETED",
}
